import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import { Providers } from './providers'
import Template from "./template"
import { Box, ChakraProvider } from "@chakra-ui/react"
import Navbar from "../components/Navbar"
import Footer from "../components/Footer"

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Carl Xircus",
  description: "Generated by create next app",
};
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <ChakraProvider>
          <Template>
            <Navbar />
            <Box id="home"
              margin={{
                base: "8",
                md: "12",
              }}
              mt={{
                base: "24",
                md: "32",
              }}
            >
              {children}
            </Box>
          </Template>
          <Footer />
        </ChakraProvider>
      </body>
    </html >
  );
}
